### ISSUE TITLE
Large installation. Is a large sample folder really necessary?

### ISSUE THREAD

**Issue by jackliu97** [muesli/smartcrop#16]
`go get` takes a long time I believe because of the size of all the images in the sample folder. Are all those images necessary for the unit tests?

**Comment by muesli** [comment]
We could and probably should put them elsewhere, agreed.

**Comment by sharpner** [comment]
We could also move the go files on the same level as the sample files 
./samples/
./crop/

that way we could install this library by using 
```
go get github.com/muesli/smartcrop/crop
```
without actually needing the sample files...

**Comment by muesli** [comment]
The only thing I dislike about that is it changing the import namespace to "crop". Using .../smartcrop/smartcrop looks a bit weird, but might be preferable in that case.

**Comment by sharpner** [comment]
yeah that would be better!

**Comment by muesli** [comment]
I've moved the sample images to https://github.com/muesli/smartcrop-samples.
