### ISSUE TITLE
Is this repository still alive?

### ISSUE THREAD

**Issue by sharpner** [muesli/smartcrop#17]
There are many issues that are necessary for this repository to be useful again,

- [ ] Remove fmt.Printf from source code
- [ ] Update dep from code.google.com/p/draw2d/draw2d to its new repo
- [ ] issue #14 

I would submit pull requests if you'd like, but if you've already abadoned this repository I'd rather fork it. 

What do you think? :/ would be a waste, since I think many people need this nowadays.

**Comment by muesli** [comment]
Certainly is :-)

**Comment by sharpner** [comment]
awesome :-)

**Comment by muesli** [comment]
Just to clarify, I'll happily merge any reasonable pull requests. We're also working on a more reliable face detection in smartcrop.

**Comment by sharpner** [comment]
Thats awesome :) thank You very much.
