### ISSUE TITLE
Strategy for improving crops that miss

### ISSUE THREAD

**Issue by dancrew32** [muesli/smartcrop#29]
Hey @muesli, for most images, this library is working perfectly. Every now and then, there are crops that need a little adjustment. 

Do you have any recommendations for improving the detection/crop model for images that crop incorrectly? I'd love to come up with a workflow for throwing a few before and after images into a folder, running `./train`, etc...

It might also be interesting to collect a library of models like the `aarcascade_frontalface_alt.xml` mentioned in the readme. E.g. one for animals, sides of faces, etc...

Thanks for your time!

**Comment by dancrew32** [comment]
Ahah! I found this collection of haar cascades: https://github.com/opencv/opencv/tree/master/data/haarcascades

**Comment by muesli** [comment]
Note: I've removed face detection with opencv for now. It will return in a separate smartcrop Analyzer later.

**Comment by muesli** [comment]
Closing this for now, but feel free to comment on your findings with the haarcascades here.
