### ISSUE TITLE
Cross compile error on MacOS for Linux (opencv)

### ISSUE THREAD

**Issue by matyunin** [muesli/smartcrop#30]
When I compile binary natively on MacOS - it's all ok:

```bash
$ go build -o ./warehouse-macos github.com/me/warehouse/cmd/warehouse
$ ls -lh ./warehouse-macos
-rwxr-xr-x  1 user  user   9.2M Apr 24 16:22 ./warehouse-macos
```

But when I try to compile on MacOS for Linux I get an error:

```bash
$ GOOS=linux GOARCH=amd64 go build -o ./warehouse-linux github.com/me/warehouse/cmd/warehouse
# github.com/muesli/smartcrop
../../../../muesli/smartcrop/crop.go:440: undefined: opencv.LoadHaarClassifierCascade
../../../../muesli/smartcrop/crop.go:443: undefined: opencv.FromImage
```

What I doing wrong?

**Comment by dancrew32** [comment]
Just checking: did you ````sudo apt-get install libcv-dev libopencv-dev libopencv-contrib-dev libhighgui-dev libopencv-photo-dev libopencv-imgproc-dev libopencv-stitching-dev libopencv-superres-dev libopencv-ts-dev libopencv-videostab-dev -y```?

**Comment by matyunin** [comment]
@dancrew32 it's macos, it hasn't `apt-get`. I installed dependencies via `brew`. As you can see above - I successfully compiled a native macos binary. But when I specify another `GOOS/GOARCH` it fails.

**Comment by muesli** [comment]
You will need the Linux versions of those libraries on your Mac then, otherwise you can't cross-compile for Linux.

**Comment by matyunin** [comment]
@muesli may be it's worth to explain users how to place a native linux libraries on mac for cross-compiling? I didn't found anything useful in google 😞  It will be nice 🙏
